Repository ASAP-as-soon-as-possible/ASAP_Client, pull requests merged in 2023-07, with the labels that each got.

#2 Feat/#1 issue 테스팅
  src/pages/Test.tsx
Labels: feat, 재훈

#8 Feat/router/#7
  package.json
  src/App.tsx
  src/Router.jsx
  yarn.lock
Labels: feat, 재훈

#14 Feat/svgComponent/#4
  package.json
  src/Router.jsx
  src/Router.tsx
  src/assets/svgs/backBtn.svg
  src/assets/svgs/clock.svg
  src/assets/svgs/dropDownBtn.svg
  src/assets/svgs/dropUpBtn.svg
  src/assets/svgs/exitIcon.svg
  src/assets/svgs/hambergerIcon.svg
  src/assets/svgs/inputCancelBtn.svg
  src/assets/svgs/inputErrorBtn.svg
  src/assets/svgs/linkIcon.svg
  src/assets/svgs/mainLogo.svg
  src/assets/svgs/passwordEye.svg
  src/assets/svgs/passwordOpenEye.svg
  src/assets/svgs/placeIcon.svg
  src/assets/svgs/plusBtn.svg
  src/assets/svgs/radioCheck.svg
  src/assets/svgs/radioChecked.svg
  src/assets/svgs/react.svg
  src/components/Icon/asset.d.ts
  src/components/Icon/icon.ts
  src/pages/ComponentTesting.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feat, 찬우, size/L

#17 Feat/mobile view/#6
  .eslintrc.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/pages/ComponentTesting.tsx
  src/pages/LibraryTP.tsx
  src/styles/globalStyles.ts
  yarn.lock
Labels: feat, 재훈, size/L

#18 Feat/reuseComponent/#15
  .eslintrc.json
  src/components/atomComponents/Button.tsx
  src/components/atomComponents/Text.tsx
  src/components/atomComponents/TextInput.tsx
  src/pages/ComponentTesting.tsx
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: feat, 찬우, size/L

#24 Fix/reuseESlint/#20
  .prettierrc
Labels: fix, 재훈, size/XS

#23 Feat/reuseComponentFix/#22
  src/components/atomComponents/Text.tsx
  src/components/atomComponents/TextInput.tsx
  src/pages/ComponentTesting.tsx
  tsconfig.json
  vite.config.ts
Labels: fix, 찬우, size/L

#31 Feat/router/#30
  src/App.tsx
  src/Router.tsx
  tsconfig.json
Labels: feat, 재훈, size/S

#33 feat/refactorCreateMeeting/#29
  src/Router.tsx
  src/components/atomComponents/Button.tsx
  src/components/atomComponents/PasswordInput.tsx
  src/components/atomComponents/PlaceInput.tsx
  src/components/atomComponents/TextAreaInput.tsx
  src/components/atomComponents/TextInput.tsx
  src/components/moleculesComponents/Header.tsx
  src/components/moleculesComponents/TitleComponent.tsx
  src/pages/createMeeting/CreateMetting.tsx
  src/pages/createMeeting/components/ReturnBodyComponent.tsx
  src/pages/createMeeting/components/ReturnTitleComponent.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/createMeeting/components/useFunnel/SetDates.tsx
  src/pages/createMeeting/components/useFunnel/SetDuration.tsx
  src/pages/createMeeting/components/useFunnel/SetHostInfo.tsx
  src/pages/createMeeting/components/useFunnel/SetPlace.tsx
  src/pages/createMeeting/components/useFunnel/SetTimes.tsx
  src/pages/createMeeting/components/useFunnel/SetTitle.tsx
  src/pages/createMeeting/data/meetingInfoData.ts
  src/pages/createMeeting/types/useFunnelInterface.ts
Labels: 찬우, 리팩토링중, size/XXL

#39 Feat/recoil/#37
  package.json
  src/Router.tsx
  src/main.tsx
  yarn.lock
Labels: feat, 재훈, size/S

#38 [Feat/available schedule view/#27] 회의 선택지에 따른 시간표 구조 구현
  src/Router.tsx
  src/pages/AvailableSchedule/AvailableSchedule.tsx
  src/pages/AvailableSchedule/components/Column.tsx
  src/pages/AvailableSchedule/components/Row.tsx
  src/pages/AvailableSchedule/components/TimeTable.tsx
  src/pages/AvailableSchedule/types/AvailableScheduleType.ts
  src/pages/AvailableSchedule/utils/getTimeSlots.ts
  src/pages/LibraryTP.tsx
  src/pages/ScrollerComponent.tsx
  src/pages/Test.css
  src/pages/Test.tsx
Labels: feat, 은서, size/XL, design

#41 designReview: creatingMeetfeedback
  src/components/atomComponents/PasswordInput.tsx
  src/components/atomComponents/PlaceInput.tsx
  src/components/atomComponents/Text.tsx
  src/components/atomComponents/TextAreaInput.tsx
  src/components/atomComponents/TextInput.tsx
  src/pages/createMeeting/CreateMeeting.tsx
Labels: fix, size/S

#48 [Feat/calendar v2/#35] 방만들기 달력 뷰 완료.
  package.json
  src/atoms/atom.ts
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/createMeeting/components/useFunnel/SetDates.css
  src/pages/createMeeting/components/useFunnel/SetDates.tsx
  src/styles/theme.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feat, 동헌, size/L, design

#47 [Feat/available schedule view/#43] 가능 시간 입력 뷰
  src/pages/AvailableSchedule/AvailableSchedule.tsx
  src/pages/AvailableSchedule/components/Column.tsx
  src/pages/AvailableSchedule/components/Row.tsx
  src/pages/AvailableSchedule/components/TimeTable.tsx
  src/pages/AvailableSchedule/types/AvailableScheduleType.ts
Labels: feat, 은서, size/L, design

#63 Feat/change view button/#62 회의 일정 확정 화면 전환 기능
  .env
  package.json
  src/Router.tsx
  src/pages/ChangeView.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
Labels: feat, 동헌, size/L, design

#58 Feat/time select box/#32
  src/Router.tsx
  src/components/Icon/icon.ts
  src/hooks/useDetectClose.ts
  src/pages/selectSchdule/SelectPage.tsx
  src/pages/selectSchdule/components/DateDropDown.tsx
  src/pages/selectSchdule/components/DateSelect.tsx
  src/pages/selectSchdule/components/SelectSchedule.tsx
  src/pages/selectSchdule/components/TimeDropDown.tsx
  src/pages/selectSchdule/components/TimeSelect.tsx
  src/pages/selectSchdule/components/dummyData.ts
  src/pages/selectSchdule/types/Schedule.ts
  src/pages/selectTime/SelectTime.tsx
  src/recoil/atoms/dateAtom.ts
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: feat, 재훈, size/XL

#54 Feat/copyToLink/#53
  package.json
  src/pages/cueCard/CueCard.tsx
  yarn.lock
Labels: fix, 찬우, size/S

#50 Feat/steppingStone view/#45
  src/Router.tsx
  src/assets/images/steppingCheck.png
  src/assets/images/steppingFinish.png
  src/assets/images/steppingInsert.png
  src/assets/images/steppingPlus.png
  src/components/atomComponents/Button.tsx
  src/components/moleculesComponents/Header.tsx
  src/pages/SteppingStone/SteppingLayout.tsx
  src/pages/SteppingStone/components/SteppingBody.tsx
  src/pages/SteppingStone/components/SteppingBtnSection.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/cueCard/CueCard.tsx
Labels: 찬우, size/L, design

#49 Feat/errorLoadingPage/#46
  src/Router.tsx
  src/assets/images/Error404.png
  src/components/atomComponents/Button.tsx
  src/components/atomComponents/PasswordInput.tsx
  src/components/atomComponents/PlaceInput.tsx
  src/components/moleculesComponents/Header.tsx
  src/pages/ErrorLoading/ErrorPage404.tsx
  src/pages/ErrorLoading/LoadingPage.tsx
Labels: 찬우, size/L, design

#69 Feat/best meet time/#60
  src/Router.tsx
  src/assets/svgs/dropdownWhite.svg
  src/assets/svgs/dropupWhite.svg
  src/assets/svgs/radioCheck.svg
  src/assets/svgs/radioChecked.svg
  src/components/Icon/icon.ts
  src/components/atomComponents/Text.tsx
  src/components/moleculesComponents/Header.tsx
  src/components/moleculesComponents/TitleComponent.tsx
  src/pages/BestMeetTime/BestMeetTime.tsx
  src/pages/BestMeetTime/ChooseBestTime.tsx
  src/pages/BestMeetTime/components/AlternativeCard.tsx
  src/pages/BestMeetTime/components/BestTimeCard.tsx
  src/pages/BestMeetTime/types/meetCardData.ts
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
Labels: feat, size/XL, design

#64 [Feat/prioritization/#57] 우선 순위 선정
  src/Router.tsx
  src/components/scheduleComponents/components/Column.tsx
  src/components/scheduleComponents/components/Row.tsx
  src/components/scheduleComponents/components/TimeTable.tsx
  src/components/scheduleComponents/data/availableDates.ts
  src/components/scheduleComponents/data/preferTimes.ts
  src/components/scheduleComponents/data/selectedSchedule.ts
  src/components/scheduleComponents/types/AvailableScheduleType.ts
  src/components/scheduleComponents/utils/getTimeSlots.ts
  src/components/scheduleComponents/utils/priorityToColor.ts
  src/pages/AvailableSchedule/AvailableSchedule.tsx
  src/pages/Prioritization/Prioritization.tsx
Labels: feat, 은서, size/L

#73 배포 라우팅 처리
  vercel.json
Labels: size/XS

#74 fix: 중복 라우터 제거
  src/Router.tsx
Labels: size/XS

#75 fix: ErrorPage router div 제거
  src/Router.tsx
Labels: size/XS

#66 Feat/create meeting api/#51 방생성하기 Post API 연결
  .env
  package-lock.json
  package.json
  src/pages/ApiTesting.tsx
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/cueCard/components/CueCardTitle.tsx
  src/types/createMeetingType.ts
  src/utils/apis/axios.ts
  src/utils/apis/createMeetingApi.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feat, 동헌, size/L

#85 [Feat/available schedule select/#71]
  src/Router.tsx
  src/assets/svgs/speechBubble.svg
  src/components/Icon/icon.ts
  src/components/moleculesComponents/Header.tsx
  src/components/moleculesComponents/TitleComponents.tsx
  src/components/scheduleComponents/components/Row.tsx
  src/components/scheduleComponents/components/TimeTable.tsx
  src/components/scheduleComponents/utils/getTimeSlots.ts
  src/pages/ApiTesting.tsx
  src/pages/BestMeetTime/BestMeetTime.tsx
  src/pages/LoginEntrance/components/HostComponent.tsx
  src/pages/LoginEntrance/components/MemberComponent.tsx
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/createMeeting/components/ReturnTitleComponent.tsx
  src/pages/selectSchdule/SelectPage.tsx
  src/pages/selectSchdule/components/DateDropDown.tsx
  src/pages/selectSchdule/components/DateSelect.tsx
  src/pages/selectSchdule/components/EndTimeDropDown.tsx
  src/pages/selectSchdule/components/EndTimeSelect.tsx
  src/pages/selectSchdule/components/SelectSchedule.tsx
  src/pages/selectSchdule/components/TimeDropDown.tsx
  src/pages/selectSchdule/components/TimeSelect.tsx
  src/pages/selectSchdule/types/Schedule.ts
  src/pages/selectSchdule/utils/addThirtyMinutesToLastElement.ts
  src/pages/selectTime/SelectTime.tsx
  src/styles/theme.ts
Labels: feat, 은서, size/L

#77 feat: 카카오톡 인앱브라우저 우회해서 타 브라우저로 열람하는 코드파일
  index.html
  src/App.tsx
  src/utils/changeBrowser.ts
Labels: feat, fix, 찬우, size/M

#80 feat: Edit ErrorPageDesign
  src/pages/ErrorLoading/ErrorPage404.tsx
Labels: fix, 찬우, size/M, design

#83 feat: add memberScheduleComplete Router
  src/Router.tsx
  src/pages/SteppingStone/components/SteppingBtnSection.tsx
Labels: feat, size/S

#92 Feat/meetCompleteRouting/#84
  .env
  src/pages/SteppingStone/components/SteppingBtnSection.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
Labels: feat, 찬우, size/M

#93 Feat/host schedule complete view routing/#86
  src/pages/SteppingStone/components/SteppingBtnSection.tsx
Labels: feat, 찬우, size/S

#95 localStorage token save and use
  src/pages/LoginEntrance/LoginEntrance.tsx
  src/pages/SteppingStone/SteppingLayout.tsx
  src/styles/theme.ts
  src/utils/apis/axios.ts
Labels: feat, 찬우, size/M

#89 Feat/setTimes/#65
  src/assets/svgs/dropdownBtnArrow.svg
  src/assets/svgs/wave.svg
  src/components/Icon/icon.ts
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/createMeeting/components/StartDropDown.tsx
  src/pages/createMeeting/components/useFunnel/SetDates.tsx
  src/pages/createMeeting/components/useFunnel/SetTimes.tsx
  src/pages/createMeeting/data/meetingInfoData.ts
  src/pages/createMeeting/types/useFunnelInterface.ts
  src/pages/selectSchdule/components/SelectSchedule.tsx
Labels: feat, 재훈, size/L

#98 [Feat/availble schedule api/#94] 가능 시간 입력 선택지 조회 GET API 연결
  .env
  src/atoms/atom.ts
  src/components/scheduleComponents/components/TimeTable.tsx
  src/pages/selectSchdule/SelectPage.tsx
  src/pages/selectSchdule/types/Schedule.ts
  src/recoil/atoms/dateAtom.ts
  src/types/availbleScheduleType.ts
  src/utils/apis/availbleScheduleOptionApi.ts
  src/utils/apis/axios.ts
Labels: feat, 은서, size/L

#102 Feat/confirm meet modal api/#67 최종 회의 확정 모달 제작 및 API 초안
  .env
  src/pages/BestMeetTime/BestMeetTime.tsx
  src/pages/BestMeetTime/ChooseBestTime.tsx
  src/pages/BestMeetTime/components/AlternativeCard.tsx
  src/pages/BestMeetTime/components/BestTimeCard.tsx
  src/pages/BestMeetTime/components/confirmModal.tsx
  src/pages/BestMeetTime/types/meetCardData.ts
  src/types/bestMeetTimeType.ts
  src/utils/apis/bestMeetTimeApi.ts
Labels: feat, 동헌, size/L, design

#103 [Fix/availableScheduleSelectDescription/#88] 회의 상세 설명 문구 조건부 처리 완료
  src/pages/selectSchdule/SelectPage.tsx
  src/types/availbleScheduleType.ts
Labels: fix, 은서, size/L

#100 Feat/isConfirmedQcard/#87
  src/pages/SteppingStone/SteppingLayout.tsx
  src/utils/apis/axios.ts
Labels: feat, 찬우, size/S

#106 Feat/get best time api/#99
  src/pages/BestMeetTime/BestMeetTime.tsx
  src/pages/BestMeetTime/components/AlternativeCard.tsx
  src/pages/BestMeetTime/components/BestTimeCard.tsx
  src/pages/BestMeetTime/components/confirmModal.tsx
  src/pages/BestMeetTime/types/meetCardData.ts
  src/utils/apis/bestMeetTimeApi.ts
Labels: feat, 동헌, size/L

#107 Feat/priority dd view/#90
  package.json
  src/Router.tsx
  src/assets/svgs/circle1.svg
  src/assets/svgs/circle2.svg
  src/assets/svgs/circle3.svg
  src/atoms/atom.ts
  src/components/Icon/icon.ts
  src/components/scheduleComponents/components/PriorityDropdown.tsx
  src/pages/selectSchdule/SelectPage.tsx
  yarn.lock
Labels: feat, 재훈, size/L

#114 Feat/priority view/#111
  src/components/atomComponents/Button.tsx
  src/components/scheduleComponents/components/PriorityDropdown.tsx
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/selectSchedule/SelectPriorityPage.tsx
  src/types/createAvailableSchduleType.ts
  src/utils/apis/createAvailableSchedule.ts
Labels: feat, 재훈, size/L

#115 Feat/confirmMeetimeApi/#105
  src/Router.tsx
  src/atoms/atom.ts
  src/components/atomComponents/TextInput.tsx
  src/components/moleculesComponents/Header.tsx
  src/components/scheduleComponents/components/TimeTable.tsx
  src/pages/BestMeetTime/BestMeetTime.tsx
  src/pages/BestMeetTime/ChooseBestTime.tsx
  src/pages/BestMeetTime/components/bestMeetTime/AlternativeCard.tsx
  src/pages/BestMeetTime/components/bestMeetTime/BestMeetTime.tsx
  src/pages/BestMeetTime/components/bestMeetTime/BestTimeCard.tsx
  src/pages/BestMeetTime/components/bestMeetTime/BlankMeetCard.tsx
  src/pages/BestMeetTime/components/bestMeetTime/confirmModal.tsx
  src/pages/ErrorLoading/LoadingPage.tsx
  src/pages/LoginEntrance/components/HostComponent.tsx
  src/pages/LoginEntrance/components/MemberComponent.tsx
  src/pages/LoginEntrance/components/ReturnModal.tsx
  src/pages/SteppingStone/components/SteppingBtnSection.tsx
  src/utils/apis/axios.ts
  src/utils/apis/bestMeetTimeApi.ts
Labels: feat, 찬우, size/XL

#116 Feat/toastLoading/#112
  package.json
  src/App.tsx
  src/components/moleculesComponents/Header.tsx
  src/pages/SteppingStone/components/SteppingBtnSection.tsx
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/createMeeting/components/useFunnel/SetDuration.tsx
  src/pages/createMeeting/data/meetingInfoData.ts
  src/pages/cueCard/CueCard.tsx
  src/utils/toast/ToastContainer.tsx
  src/utils/toast/copyLink.ts
  yarn.lock
Labels: feat, 찬우, size/L

#117 Feat/priority view/#111
  src/atoms/atom.ts
  src/components/scheduleComponents/components/PriorityDropdown.tsx
  src/pages/SteppingStone/components/SteppingBtnSection.tsx
  src/pages/selectSchedule/SelectPriorityPage.tsx
  src/pages/selectSchedule/SelectSchedulePage.tsx
Labels: feat, 재훈, size/M

#119 deploy ts 검사
  src/pages/BestMeetTime/components/bestMeetTime/AlternativeCard.tsx
  src/pages/createMeeting/components/useFunnel/SetPlace.tsx
Labels: size/S

#120 [Feat/overall schedule/#104] 종합 일정 시간표 뷰 구현 및 API 연결
  src/atoms/atom.ts
  src/components/scheduleComponents/types/AvailableScheduleType.ts
  src/pages/OverallSchedule/OverallSchedule.tsx
  src/pages/OverallSchedule/components/Column.tsx
  src/pages/OverallSchedule/components/Row.tsx
  src/pages/OverallSchedule/components/TimeTable.tsx
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/selectSchedule/SelectSchedulePage.tsx
  src/types/overallScheduleType.ts
  src/utils/apis/overallScheduleApi.ts
Labels: feat, 은서, size/XL

#128 [Feat/overall schedule description/#122] 종합 일정 시간표 추가정보 및 클릭시 색상 변경
  src/atoms/atom.ts
  src/components/scheduleComponents/types/AvailableScheduleType.ts
  src/pages/LoginEntrance/components/HostComponent.tsx
  src/pages/OverallSchedule/OverallSchedule.tsx
  src/pages/OverallSchedule/components/Column.tsx
  src/pages/OverallSchedule/components/Row.tsx
  src/pages/selectSchedule/SelectPriorityPage.tsx
Labels: feat, 은서

#130 fix: 종합 일정 시간표 에러핸들링
  src/pages/OverallSchedule/OverallSchedule.tsx
  src/pages/OverallSchedule/components/Row.tsx
  src/pages/OverallSchedule/utils/getFormattedAvailableDateTimes.ts
Labels: fix, 은서

#131 Feat/user post api/#126
  src/atoms/atom.ts
  src/pages/LoginEntrance/components/MemberComponent.tsx
  src/pages/selectSchedule/SelectModal.tsx
  src/pages/selectSchedule/SelectPriorityPage.tsx
  src/pages/selectSchedule/SelectSchedulePage.tsx
  src/pages/selectSchedule/utils/changeApiReq.ts
  src/pages/selectSchedule/utils/changeHostApiReq.ts
  src/utils/apis/createHostAvailableSchedule.ts
Labels: feat, 재훈, size/L

#132 Feat/refactor hooks/#123
  src/App.tsx
  src/components/moleculesComponents/Header.tsx
  src/components/scheduleComponents/components/PriorityDropdown.tsx
  src/pages/BestMeetTime/components/bestMeetTime/AlternativeCard.tsx
  src/pages/BestMeetTime/components/bestMeetTime/BestMeetTime.tsx
  src/pages/BestMeetTime/components/bestMeetTime/BestTimeCard.tsx
  src/pages/BestMeetTime/components/bestMeetTime/confirmModal.tsx
  src/pages/BestMeetTime/hooks/getBestMeetimeList.ts
  src/pages/BestMeetTime/utils/whatisBestMeetime.ts
  src/pages/SteppingStone/components/SteppingBody.tsx
  src/pages/SteppingStone/components/SteppingBtnSection.tsx
  src/pages/createMeeting/components/useFunnel/SetHostInfo.tsx
  src/pages/cueCard/CueCard.tsx
  src/pages/cueCard/components/Qcard.tsx
  src/pages/cueCard/hooks/getQCardData.ts
  src/pages/cueCard/types/cueCardType.ts
  src/pages/selectSchedule/components/DateDropDown.tsx
  src/utils/toast/copyLink.ts
Labels: size/XL

#133 fix: ts 오류
  src/components/atomComponents/PasswordInput.tsx
  src/components/atomComponents/TextInput.tsx
  src/pages/BestMeetTime/ChooseBestTime.tsx
  src/pages/BestMeetTime/components/bestMeetTime/AlternativeCard.tsx
  src/pages/BestMeetTime/components/bestMeetTime/BestMeetTime.tsx
  src/pages/BestMeetTime/components/bestMeetTime/BestTimeCard.tsx
Labels: size/L

#138 Fix/dropdown qa/#134
  src/components/scheduleComponents/utils/compareTime.ts
  src/components/scheduleComponents/utils/getTimeSlots.ts
  src/pages/selectSchedule/SelectPriorityPage.tsx
  src/pages/selectSchedule/SelectSchedulePage.tsx
  src/pages/selectSchedule/components/SelectSchedule.tsx
Labels: feat, 재훈, size/M

#140 [fix: OverallSchedule/components/Column.tsx ts오류 수정] (심은서)
  src/components/scheduleComponents/components/Column.tsx
  src/pages/OverallSchedule/OverallSchedule.tsx
  src/pages/OverallSchedule/components/Column.tsx
Labels: size/S

#148 feat: favicon 적용
  index.html
  public/favicon.ico
Labels: feat, size/XS

#151 deploy: env edit
  .env
  src/components/moleculesComponents/Header.tsx
  src/pages/SteppingStone/components/SteppingBtnSection.tsx
Labels: size/XS

#153 fix: loginMember 토큰 삭제
  src/pages/LoginEntrance/components/MemberComponent.tsx
Labels: size/XS

#155 [fix: 시간표 emptydate에 대해 grey9 적용]
  src/components/scheduleComponents/components/Column.tsx
  src/components/scheduleComponents/utils/priorityToColor.ts
  src/pages/selectSchedule/SelectSchedulePage.tsx
Labels: fix, 은서, size/S

#156 Hotfix/#154
  src/pages/LoginEntrance/components/MemberComponent.tsx
  src/pages/OverallSchedule/OverallSchedule.tsx
  src/pages/OverallSchedule/components/Column.tsx
  src/pages/OverallSchedule/components/Row.tsx
  src/pages/OverallSchedule/utils/setUserNames.ts
  src/pages/selectSchedule/SelectModal.tsx
  src/pages/selectSchedule/SelectSchedulePage.tsx
  src/utils/apis/overallScheduleApi.ts
Labels: feat, 재훈, size/M

#157 deploy final
  README.md
  src/components/scheduleComponents/components/Column.tsx
  src/components/scheduleComponents/components/Row.tsx
  src/components/scheduleComponents/utils/compareTime.ts
  src/components/scheduleComponents/utils/priorityToColor.ts
  src/pages/BestMeetTime/components/bestMeetTime/BestMeetTime.tsx
  src/pages/BestMeetTime/hooks/getBestMeetimeList.ts
  src/pages/OverallSchedule/OverallSchedule.tsx
  src/pages/OverallSchedule/components/Column.tsx
  src/pages/OverallSchedule/components/Row.tsx
  src/pages/OverallSchedule/utils/setUserNames.ts
  src/pages/createMeeting/components/useFunnel/SetTimes.tsx
  src/pages/cueCard/components/Qcard.tsx
  src/pages/cueCard/hooks/getQCardData.ts
  src/pages/cueCard/types/cueCardType.ts
  src/pages/selectSchedule/SelectModal.tsx
  src/pages/selectSchedule/SelectSchedulePage.tsx
  src/styles/globalStyles.ts
  src/utils/apis/overallScheduleApi.ts
Labels: size/L

#158 feat: 링크 이미지 공유
  index.html
  public/mainLogo.png
Labels: size/XS

#163 [Feat/tally insert/#161] Navigation 피드백 남기기에 Tally 달기
  src/components/moleculesComponents/Header.tsx
  src/components/moleculesComponents/Navigation.tsx
Labels: feat, 은서, size/M
