Repository ASAP-as-soon-as-possible/ASAP_Client, pull requests merged in 2024-08, with the labels that each got.

#304 [Fix/#303] styled-components/macro를 styled-components로 변경
  .stylelintrc
  src/App.tsx
  src/components/common/atomComponents/PasswordInput.tsx
  src/components/common/atomComponents/PlaceInput.tsx
  src/components/common/atomComponents/Text.tsx
  src/components/common/atomComponents/TextAreaInput.tsx
  src/components/common/atomComponents/TextInput.tsx
  src/components/common/moleculesComponents/Header.tsx
  src/components/common/moleculesComponents/TitleComponents.tsx
  src/components/legacy/scheduleComponents/components/PriorityDropdown.tsx
  src/pages/ComponentTesting.tsx
  src/pages/bestMeetTime/components/AlternativeCard.tsx
  src/pages/bestMeetTime/components/BestMeetTime.tsx
  src/pages/bestMeetTime/components/BestTimeCard.tsx
  src/pages/bestMeetTime/components/BlankMeetCard.tsx
  src/pages/bestMeetTime/components/ConfirmModal.tsx
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/createMeeting/components/ReturnBodyComponent.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/createMeeting/components/useFunnel/SetDates.tsx
  src/pages/createMeeting/components/useFunnel/SetDuration.tsx
  src/pages/createMeeting/components/useFunnel/SetHostInfo.tsx
  src/pages/createMeeting/components/useFunnel/SetPlace.tsx
  src/pages/createMeeting/components/useFunnel/SetTitle.tsx
  src/pages/cueCard/CueCard.tsx
  src/pages/cueCard/components/CueCardTitle.tsx
  src/pages/cueCard/components/Qcard.tsx
  src/pages/errorLoading/ErrorPage404.tsx
  src/pages/errorLoading/LoadingPage.tsx
  src/pages/legacy/selectSchedule/SelectModal.tsx
  src/pages/loginEntrance/LoginEntrance.tsx
  src/pages/loginEntrance/components/HostComponent.tsx
  src/pages/loginEntrance/components/IncorrectInfoModal.tsx
  src/pages/loginEntrance/components/MemberComponent.tsx
  src/pages/loginEntrance/components/NoAvailableTimeModal.tsx
  src/pages/onBoarding/OnBoarding.tsx
  src/pages/onBoarding/components/Explain.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
  src/pages/steppingStone/SteppingLayout.tsx
  src/pages/steppingStone/components/SteppingBody.tsx
  src/pages/steppingStone/components/SteppingBtnSection.tsx
  src/utils/toast/ToastContainer.tsx
Labels: fix, size/M

#308 [Fix/#307] 방장 로그인 403에러시 새로 반환된 토큰 저장
  src/pages/loginEntrance/components/HostComponent.tsx
Labels: fix, size/XS

#295 [Fix/#294] 우선순위 입력 페이지에서 가능시간 입력 페이지로 되돌아가면 우선순위 초기화
  .github/workflows/CI.yml
  src/components/common/moleculesComponents/Header.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityCta.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
  src/pages/selectSchedule/components/selectTimeSlot/SelectionColumn.tsx
  src/pages/selectSchedule/components/selectTimeSlot/TimeSlotCta.tsx
Labels: fix, 재훈, size/L, refactor

#312 [Fix/#311] 뒤로가기 로직 수정
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/legacy/selectSchedule/SelectModal.tsx
  src/pages/loginEntrance/components/MemberComponent.tsx
  src/pages/loginEntrance/components/NoAvailableTimeModal.tsx
  src/pages/onBoarding/OnBoarding.tsx
  src/pages/selectSchedule/SelectSchedule.tsx
  src/pages/selectSchedule/components/selectTimeSlot/TimeSlotCta.tsx
  src/pages/steppingStone/SteppingLayout.tsx
  src/pages/steppingStone/components/SteppingBtnSection.tsx
Labels: fix, 은서, size/L

#313 [Feat/#296] 회의 생성 전 확인 바텀시트 구현
  src/components/common/BottomSheet/BottomSheet.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/createMeeting/components/useFunnel/SetPlace.tsx
  src/pages/createMeeting/data/meetingInfoData.ts
  src/pages/selectSchedule/components/selectTimeSlot/TimeSlotCta.tsx
  src/pages/steppingStone/components/SteppingBtnSection.tsx
Labels: feat, 은서, size/L

#314 [BUILD FAIL] [Feat/#300] tooltip 구현 & 회의 생성 완료 페이지 분리, 리팩토링
  src/Router.tsx
  src/assets/svgs/linkTooltip.svg
  src/assets/svgs/tooltipArrow.svg
  src/components/Icon/icon.ts
  src/components/common/moleculesComponents/CheckPoint.tsx
  src/components/common/moleculesComponents/Header.tsx
  src/pages/completeCreateMeeting/CompleteCreateMeeting.tsx
  src/pages/completeCreateMeeting/components/CreateMeetingBottomSheet.tsx
  src/pages/completeCreateMeeting/components/Tooltip.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/cueCard/CueCard.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
  src/pages/steppingStone/SteppingLayout.tsx
  src/pages/steppingStone/components/SteppingBody.tsx
  src/pages/steppingStone/components/SteppingBtnSection.tsx
  src/utils/toast/ToastContainer.tsx
  src/utils/toast/copyLinkToast.ts
Labels: feat, 재훈, size/L

#322 [Hotfix/#321] 머지과정에서 중복된 선언 머지된 부분 수정
  src/components/Icon/icon.ts
Labels: size/S, hotfix

#317 [Feat/#315] priority dropdown 취소 기능 구현
  src/assets/svgs/arrowBottom.svg
  src/assets/svgs/arrowTop.svg
  src/components/Icon/icon.ts
  src/components/legacy/scheduleComponents/components/PriorityDropdown.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
Labels: feat, 재훈, size/L

#319 [Fix/#318] 방장 및 참여자 이름 입력 제한 글자수 8자로 변경
  src/components/common/atomComponents/TextInput.tsx
  src/pages/createMeeting/components/useFunnel/SetHostInfo.tsx
  src/pages/createMeeting/components/useFunnel/SetTitle.tsx
  src/pages/loginEntrance/components/HostComponent.tsx
  src/pages/loginEntrance/components/MemberComponent.tsx
Labels: fix, 은서, size/S

#324 [Feat/#323] 430기준으로 반응형 뷰 적용
  src/App.tsx
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/common/atomComponents/Button.tsx
  src/components/common/atomComponents/PasswordInput.tsx
  src/components/common/atomComponents/PlaceInput.tsx
  src/components/common/atomComponents/TextAreaInput.tsx
  src/components/common/atomComponents/TextInput.tsx
  src/components/common/moleculesComponents/BottomBtnSection.tsx
  src/components/common/timetableComponents/Timetable.tsx
  src/pages/bestMeetTime/ChooseBestTime.tsx
  src/pages/bestMeetTime/components/BestMeetTime.tsx
  src/pages/bestMeetTime/components/BestTimeCard.tsx
  src/pages/bestMeetTime/components/BlankMeetCard.tsx
  src/pages/bestMeetTime/hooks/getBestMeetimeList.ts
  src/pages/completeCreateMeeting/CompleteCreateMeeting.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/createMeeting/components/useFunnel/SetDates.css
  src/pages/createMeeting/components/useFunnel/SetDates.tsx
  src/pages/createMeeting/components/useFunnel/SetDuration.tsx
  src/pages/createMeeting/components/useFunnel/SetHostInfo.tsx
  src/pages/createMeeting/components/useFunnel/SetPlace.tsx
  src/pages/createMeeting/components/useFunnel/SetTitle.tsx
  src/pages/cueCard/CueCard.tsx
  src/pages/errorLoading/ErrorPage404.tsx
  src/pages/loginEntrance/LoginEntrance.tsx
  src/pages/loginEntrance/components/HostComponent.tsx
  src/pages/loginEntrance/components/MemberComponent.tsx
  src/pages/loginEntrance/components/NoAvailableTimeModal.tsx
  src/pages/onBoarding/OnBoarding.tsx
  src/pages/selectSchedule/components/Description.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityCta.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
  src/pages/selectSchedule/components/selectTimeSlot/TimeSlotCta.tsx
  src/pages/steppingStone/components/SteppingBody.tsx
  src/pages/steppingStone/components/SteppingBtnSection.tsx
  src/styles/globalStyles.ts
Labels: feat, 재훈, size/L

#327 [Fix/#320] 자잘한 스타일링, 라이팅 변경
  src/components/Icon/icon.ts
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/common/moleculesComponents/Header.tsx
  src/pages/createMeeting/components/ReturnTitleComponent.tsx
  src/pages/createMeeting/components/useFunnel/SetHostInfo.tsx
  src/pages/onBoarding/OnBoarding.tsx
  src/pages/selectSchedule/SelectSchedule.tsx
  src/pages/selectSchedule/components/Description.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
  src/pages/selectSchedule/components/selectTimeSlot/OnboardingLottie.tsx
  src/pages/selectSchedule/components/selectTimeSlot/SelectionColumn.tsx
Labels: fix, 은서, size/M

#328 [Fix/#326] 모달 디자인 변경
  src/pages/loginEntrance/components/IncorrectInfoModal.tsx
  src/pages/loginEntrance/components/NoAvailableTimeModal.tsx
Labels: fix, 재훈, size/M, design
