Repository ASAP-as-soon-as-possible/ASAP_Client, pull requests merged in 2024-07, with the labels that each got.

#248 fix: /time POST 요청값에서 id와 dayOfWeek 필드 삭제, month와 day에서 padStart 삭제
  src/pages/selectSchedule/utils/changeApiReq.ts
  src/types/createAvailableSchduleType.ts
Labels: size/S

#245 [Feat/#241] 종합 일정 시간표 구현
  src/components/moleculesComponents/Header.tsx
  src/components/timetableComponents/Timetable.tsx
  src/components/timetableComponents/context.ts
  src/pages/OverallSchedule/OverallSchedule.tsx
  src/pages/OverallSchedule/components/OverallScheduleColumn.tsx
  src/pages/OverallSchedule/components/OverallScheduleTable.tsx
  src/pages/OverallSchedule/components/Title.tsx
  src/pages/OverallSchedule/components/UserNames.tsx
  src/pages/OverallSchedule/contexts/useClickContext.ts
  src/pages/OverallSchedule/hooks/useSlotClick.ts
  src/pages/legacy/overallSchedule/OverallSchedule.tsx
  src/pages/legacy/overallSchedule/components/Column.tsx
  src/pages/legacy/overallSchedule/components/Row.tsx
  src/pages/legacy/overallSchedule/components/TimeTable.tsx
  src/pages/legacy/overallSchedule/utils/getFormattedAvailableDateTimes.ts
  src/pages/legacy/overallSchedule/utils/setUserNames.ts
  src/pages/legacy/selectSchedule/SelectModal.tsx
  src/pages/selectSchedule/SelectSchedule.tsx
  src/pages/selectSchedule/components/SelectScheduleTable.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityColumn.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
  src/pages/selectSchedule/components/selectTimeSlot/SelectionColumn.tsx
  src/pages/selectSchedule/components/selectTimeSlot/TimeSlotCta.tsx
  src/pages/selectSchedule/components/selectTimeSlot/hooks/useSlotSelection.ts
  src/pages/selectSchedule/contexts/useScheduleStepContext.ts
  src/pages/selectSchedule/contexts/useSelectContext.ts
  src/pages/selectSchedule/types.ts
  src/pages/selectSchedule/utils.ts
  src/types/createAvailableSchduleType.ts
  src/utils/apis/useGetOverallSchedule.ts
  src/utils/apis/useGetTimetable.ts
Labels: size/XL

#240 [Feat/#239] 가능 시간 입력 GET, POST react-query로 구현
  .eslintrc.json
  package.json
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/components/moleculesComponents/Header.tsx
  src/components/timetableComponents/Timetable.tsx
  src/components/timetableComponents/context.ts
  src/components/timetableComponents/types.ts
  src/components/timetableComponents/utils.ts
  src/pages/LoginEntrance/components/MemberComponent.tsx
  src/pages/LoginEntrance/components/NoAvailableTimeModal.tsx
  src/pages/OverallSchedule/OverallSchedule.tsx
  src/pages/OverallSchedule/components/OverallScheduleColumn.tsx
  src/pages/OverallSchedule/components/OverallScheduleTable.tsx
  src/pages/OverallSchedule/components/Title.tsx
  src/pages/OverallSchedule/components/UserNames.tsx
  src/pages/OverallSchedule/contexts/useClickContext.ts
  src/pages/OverallSchedule/hooks/useSlotClick.ts
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/legacy/overallSchedule/OverallSchedule.tsx
  src/pages/legacy/overallSchedule/components/Column.tsx
  src/pages/legacy/overallSchedule/components/Row.tsx
  src/pages/legacy/overallSchedule/components/TimeTable.tsx
  src/pages/legacy/overallSchedule/utils/getFormattedAvailableDateTimes.ts
  src/pages/legacy/overallSchedule/utils/setUserNames.ts
  src/pages/legacy/selectSchedule/SelectModal.tsx
  src/pages/legacy/selectSchedule/SelectPriorityPage.tsx
  src/pages/legacy/selectSchedule/SelectSchedulePage.tsx
  src/pages/legacy/selectSchedule/utils/changeApiReq.ts
  src/pages/onBoarding/OnBoarding.tsx
  src/pages/selectSchedule/SelectSchedule.tsx
  src/pages/selectSchedule/components/Description.tsx
  src/pages/selectSchedule/components/SelectScheduleTable.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityColumn.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
  src/pages/selectSchedule/components/selectTimeSlot/SelectionColumn.tsx
  src/pages/selectSchedule/components/selectTimeSlot/TimeSlotCta.tsx
  src/pages/selectSchedule/components/selectTimeSlot/hooks/useSlotSelection.ts
  src/pages/selectSchedule/contexts/useScheduleStepContext.ts
  src/pages/selectSchedule/contexts/useSelectContext.ts
  src/pages/selectSchedule/types.ts
  src/pages/selectSchedule/utils.ts
  src/utils/apis/bestMeetTimeApi.ts
  src/utils/apis/legacy/availbleScheduleOptionApi.ts
  src/utils/apis/legacy/createHostAvailableSchedule.ts
  src/utils/apis/legacy/createMeetingApi.ts
  src/utils/apis/legacy/cueCardAPI.ts
  src/utils/apis/legacy/overallScheduleApi.ts
  src/utils/apis/useGetOverallSchedule.ts
  src/utils/apis/useGetTimetable.ts
  yarn.lock
Labels: size/XL

#255 [Fix/#254] 큐카드 저장시 레이아웃 변경
  src/pages/cueCard/CueCard.tsx
  src/pages/cueCard/components/CueCardTitle.tsx
  src/pages/cueCard/components/Qcard.tsx
Labels: fix, size/S

#251 [Feat/#250] 탭투탭에서 블록이 겹쳐서 쌓이는 문제 해결
  src/pages/OverallSchedule/components/OverallScheduleTable.tsx
  src/pages/OverallSchedule/contexts/useClickContext.ts
  src/pages/selectSchedule/components/SelectScheduleTable.tsx
  src/pages/selectSchedule/components/selectTimeSlot/hooks/useSlotSelection.ts
  src/pages/selectSchedule/contexts/useScheduleStepContext.ts
  src/pages/selectSchedule/contexts/useSelectContext.ts
  src/pages/selectSchedule/utils/changeApiReq.ts
Labels: feat, size/L

#258 [Feat/#257] 탭투탭 아래에서 위로 선택이 가능하도록 처리
  src/pages/selectSchedule/components/selectTimeSlot/hooks/useSlotSelection.ts
Labels: feat, size/M

#253 [feat/#252] 이미 확정된 회의의 시간표를 조회하면 큐카드로 이동
  src/Router.tsx
  src/pages/LoginEntrance/components/HostComponent.tsx
  src/utils/apis/useGetTimetable.ts
Labels: feat, size/M

#264 [fix] 시간 슬롯 선택 hook 병합시 발생한 에러 수정
  src/pages/selectSchedule/components/selectTimeSlot/hooks/useSlotSelection.ts
Labels: fix, size/M

#265 main merge
  .github/workflows /deploy.yml
  src/pages/selectSchedule/components/selectTimeSlot/hooks/useSlotSelection.ts
Labels: size/M

#266 개인레포 CD 테스트
  .github/workflows/deploy.yml
  src/pages/onBoarding/OnBoarding.tsx
Labels: size/XS

#267 chore: workflows파일 하나로 만들고 action잡는지 확인해보는용도의 커밋
  src/pages/onBoarding/OnBoarding.tsx
Labels: size/XS

#273 [ Hotfix/#272 ] 시간 배열의 0번째는 시간표에 우선순위 적용안되는 이슈 해결
  src/pages/selectSchedule/components/selectPriority/PriorityColumn.tsx
Labels: size/XS, hotfix

#282 [Fix/#280] 선호시간대 입력 삭제
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/createMeeting/components/ReturnBodyComponent.tsx
  src/pages/createMeeting/components/ReturnTitleComponent.tsx
  src/pages/createMeeting/components/useFunnel/SetDates.tsx
  src/pages/createMeeting/components/useFunnel/SetTimes.tsx
  src/pages/createMeeting/data/meetingInfoData.ts
Labels: size/L, hotfix

#279 [Feat/#274] TEST build 통과 PR + yml파일 분리
  .eslintrc.json
  .stylelintrc
  src/pages/ComponentTesting.tsx
  src/pages/bestMeetTime/hooks/getBestMeetimeList.ts
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/cueCard/hooks/getQCardData.ts
  src/pages/legacy/overallSchedule/OverallSchedule.tsx
  src/pages/legacy/selectSchedule/components/DateDropDown.tsx
  src/pages/legacy/selectSchedule/components/DateSelect.tsx
  src/pages/loginEntrance/components/HostComponent.tsx
  src/pages/onBoarding/OnBoarding.tsx
  src/pages/overallSchedule/components/OverallScheduleTable.tsx
  src/pages/selectSchedule/SelectSchedule.tsx
Labels: size/L

#291 [Feat/#274] test build 통과 PR
  .eslintrc.json
  .stylelintrc
  src/pages/ComponentTesting.tsx
  src/pages/bestMeetTime/hooks/getBestMeetimeList.ts
  src/pages/createMeeting/components/useFunnel/SetAdditionalInfo.tsx
  src/pages/cueCard/hooks/getQCardData.ts
  src/pages/legacy/overallSchedule/OverallSchedule.tsx
  src/pages/legacy/selectSchedule/components/DateDropDown.tsx
  src/pages/legacy/selectSchedule/components/DateSelect.tsx
  src/pages/loginEntrance/components/HostComponent.tsx
  src/pages/onBoarding/OnBoarding.tsx
  src/pages/overallSchedule/components/OverallScheduleTable.tsx
  src/pages/selectSchedule/SelectSchedule.tsx
Labels: feat, 재훈, size/L

#290 [Fix/#284] 선호시간대 관련 api에서 preferTimes 필드 삭제
  src/atoms/atom.ts
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/createMeeting/components/StartDropDown.tsx
  src/pages/createMeeting/types/useFunnelInterface.ts
  src/pages/legacy/overallSchedule/OverallSchedule.tsx
  src/pages/legacy/overallSchedule/components/Column.tsx
  src/pages/legacy/overallSchedule/components/Row.tsx
  src/pages/legacy/overallSchedule/components/TimeTable.tsx
  src/pages/legacy/overallSchedule/utils/getFormattedAvailableDateTimes.ts
  src/pages/legacy/overallSchedule/utils/setUserNames.ts
  src/pages/legacy/selectSchedule/SelectPriorityPage.tsx
  src/pages/legacy/selectSchedule/SelectSchedulePage.tsx
  src/pages/legacy/selectSchedule/components/DateDropDown.tsx
  src/pages/legacy/selectSchedule/components/DateSelect.tsx
  src/pages/legacy/selectSchedule/components/EndTimeDropDown.tsx
  src/pages/legacy/selectSchedule/components/EndTimeSelect.tsx
  src/pages/legacy/selectSchedule/components/SelectSchedule.tsx
  src/pages/legacy/selectSchedule/components/TimeDropDown.tsx
  src/pages/legacy/selectSchedule/components/TimeSelect.tsx
  src/pages/legacy/selectSchedule/components/dummyData.ts
  src/pages/legacy/selectSchedule/selectTime/SelectTime.tsx
  src/pages/legacy/selectSchedule/utils/addThirtyMinutesToLastElement.ts
  src/pages/selectSchedule/SelectSchedule.tsx
  src/types/availbleScheduleType.ts
  src/types/createMeetingType.ts
  src/utils/apis/useGetTimetable.ts
Labels: fix, size/XXL

#293 develop to main
  src/atoms/atom.ts
  src/pages/createMeeting/CreateMeeting.tsx
  src/pages/createMeeting/components/StartDropDown.tsx
  src/pages/createMeeting/types/useFunnelInterface.ts
  src/pages/legacy/overallSchedule/OverallSchedule.tsx
  src/pages/legacy/overallSchedule/components/Column.tsx
  src/pages/legacy/overallSchedule/components/Row.tsx
  src/pages/legacy/overallSchedule/components/TimeTable.tsx
  src/pages/legacy/overallSchedule/utils/getFormattedAvailableDateTimes.ts
  src/pages/legacy/overallSchedule/utils/setUserNames.ts
  src/pages/legacy/selectSchedule/SelectPriorityPage.tsx
  src/pages/legacy/selectSchedule/SelectSchedulePage.tsx
  src/pages/legacy/selectSchedule/components/DateDropDown.tsx
  src/pages/legacy/selectSchedule/components/DateSelect.tsx
  src/pages/legacy/selectSchedule/components/EndTimeDropDown.tsx
  src/pages/legacy/selectSchedule/components/EndTimeSelect.tsx
  src/pages/legacy/selectSchedule/components/SelectSchedule.tsx
  src/pages/legacy/selectSchedule/components/TimeDropDown.tsx
  src/pages/legacy/selectSchedule/components/TimeSelect.tsx
  src/pages/legacy/selectSchedule/components/dummyData.ts
  src/pages/legacy/selectSchedule/selectTime/SelectTime.tsx
  src/pages/legacy/selectSchedule/utils/addThirtyMinutesToLastElement.ts
  src/pages/selectSchedule/SelectSchedule.tsx
  src/types/availbleScheduleType.ts
  src/types/createMeetingType.ts
  src/utils/apis/useGetTimetable.ts
Labels: size/XXL

#286 [Feat/#285] 시간표 UI 변경 및 Slot 스타일링 로직의 의존성 분리
  src/components/timetableComponents/Timetable.tsx
  src/components/timetableComponents/parts/Slot.tsx
  src/components/timetableComponents/parts/SlotTitle.tsx
  src/pages/overallSchedule/components/OverallScheduleColumn.tsx
  src/pages/overallSchedule/components/OverallScheduleTable.tsx
  src/pages/selectSchedule/components/SelectScheduleTable.tsx
  src/pages/selectSchedule/components/selectPriority/PriorityColumn.tsx
  src/pages/selectSchedule/components/selectTimeSlot/SelectionColumn.tsx
  src/pages/selectSchedule/utils.ts
Labels: feat, size/L
